#!/bin/bash

# Checking the lock
if [ -f /rtorrent/.session/rtorrent.lock ]; then
    echo
    prompt="The rTorrent session lock is detected, it can be a result of an \n"
    prompt="${prompt}unexpected exit or other running rTorrent instance.\n"
    echo -e ${prompt}
    prompt="Remove lock and continue anyway? [y/N] "
    read -r -p "${prompt}" response
    response=${response,,}
    if [[ $response =~ ^(yes|y)$ ]]; then
        rm -f /rtorrent/.session/rtorrent.lock
    else
        s6-svscanctl -t /service
    fi
fi

# Turn to rTorrent
exec rtorrent
