#!/bin/bash

# Create working directories if not exists
mkdir -p /rtorrent/{downloads,watch,.session,rutorrent/user-profiles}

# Change permission to ruTorrent's webserver user
chown -R www-data:www-data /rtorrent

# Turn to rTorrent
exec rtorrent
